site_name: Sentence Models
site_description: A slightly different take on textcat.
repo_url: https://github.com/koaning/sentence-models
theme:
  name: material
  palette:
    primary: white
  font:
    text: Roboto Mono
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/envelope-open-text
  features:
    - content.code.copy
plugins:
  - mkdocstrings:
      default_handler: python
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences