site_name: Sentence Models
theme:
  name: material
  palette:
    primary: white
  font:
    text: Roboto Mono
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/envelope-open-text
  features:
    - content.code.copy
plugins: []
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences